name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      uses: actions/setup-cpp@v1

    - name: Build and test project using Makefile
      run: |
       make
